### ISSUE TITLE
Incorrect release? Not as described.

### ISSUE THREAD

**Issue by RichyT** [cabbagecreek/STL-thumbnail#4]
I downloaded and installed this. It installs a small program that can be used to view STL files but I understood it was an Explorer extension to allow previewing thumbnails in the preview pane?

This is on Windows 7. I've tried rebooting also.

**Comment by cabbagecreek** [comment]
Try this link: http://Marlin3DprinterTool.se/LatestVersion/Marlin3DprinterTool.msi

First uninstall the M3DpT 
Then loop at C:\ Program x86\Marlin3DprinterTool and remove all files (if there is any)
Reinstall using the above msi

/J

Skickades från E-post för Windows 10

Från: RichyT
Skickat: Saturday, December 29, 2018 6:40 PM
Till: cabbagecreek/STL-thumbnail
Kopia: Subscribed
Ämne: [cabbagecreek/STL-thumbnail] Incorrect release? Not as described.(#4)

I downloaded and installed this. It installs a small program that can be used to view STL files but I understood it was an Explorer extension to allow previewing thumbnails in the preview pane?

**Comment by RichyT** [comment]
Never mind. Found there is a configuration tool that needs to be run. Working fine now. Nice tool, thanks.

**Comment by cabbagecreek** [comment]
Works even better if you have a late Win10

Happy New Year!!

/J

Skickades från E-post för Windows 10

Från: RichyT
Skickat: Saturday, December 29, 2018 6:45 PM
Till: cabbagecreek/STL-thumbnail
Kopia: Johnny Lindén; Comment
Ämne: Re: [cabbagecreek/STL-thumbnail] Incorrect release? Not as described.(#4)

Never mind. Found there is a configuration tool that needs to be run. Working fine now. Nice tool, thanks.

**Comment by RichyT** [comment]
But then you have to run Win10 :( (which I do have on my VR rig and don't like)

**Comment by cabbagecreek** [comment]
This 9month of work is ”sneaking” in the windows core.. Should work from XP and up

The STL thumbnail Shell Extension is burried Deep in windows and thats why its working in all programs that are able to do a preview when selecting a file

/J

Skickades från E-post för Windows 10

Från: RichyT
Skickat: Saturday, December 29, 2018 6:47 PM
Till: cabbagecreek/STL-thumbnail
Kopia: Johnny Lindén; Comment
Ämne: Re: [cabbagecreek/STL-thumbnail] Incorrect release? Not as described.(#4)

But then you have to run Win10 :( (which I do have on my VR rig and don't like)

**Comment by RichyT** [comment]
Do you also need to run the configuration tool for Win10? If so, might be worth mentioning on the front page of this place and maybe as a popup on install.

**Comment by cabbagecreek** [comment]
Its Always needed. Its an extension to the windows core

Skickades från E-post för Windows 10

Från: RichyT
Skickat: Saturday, December 29, 2018 6:53 PM
Till: cabbagecreek/STL-thumbnail
Kopia: Johnny Lindén; Comment
Ämne: Re: [cabbagecreek/STL-thumbnail] Incorrect release? Not as described.(#4)

Do you also need to run the configuration tool for Win10? If so, might be worth mentioning on the front page of this place and maybe as a popup on install.
